headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]
included_files = ["src/**"]
node_bundler = "esbuild"

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"
pinned_version = "5"

[plugins.inputs]

[build]
publish = "/Users/kotarokashiwai/aceoripa/aceoripa/aceoripa-claude/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]